fix:put frontend url in a secret

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -49,11 +49,10 @@ jobs:
     - name: Install pa11y-ci dependencies.
       run: npm install
 
-    - name: Check URL Accessibility
-      run: curl -I https://8ddx2p65g4.eu-west-1.awsapprunner.com/job-roles
-
     - name: Run pa11y
-      run: npm run test-accessibility > pa11y-output.txt || { echo 'Pa11y failed'; exit 1; }
+      env: 
+        FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
+      run: npm run URL_ENV=FRONTEND_URL test-accessibility > pa11y-output.txt || { echo 'Pa11y failed'; exit 1; }
 
     - name: Print Pa11y Output
       run: cat pa11y-output.txt
